import json
from datetime import datetime
from typing import Any

from app.utils.logging import logger


class ReportGenerator:
    @staticmethod
    def generate_markdown_report(
        title: str,
        summary: str,
        kpis: list[dict[str, Any]] | None = None,
        insights: list[str] | None = None,
        chart_html: list[str] | None = None,
        etl_logs: list[dict[str, Any]] | None = None,
        recommendations: list[str] | None = None,
    ) -> str:
        parts = [
            f"# {title}",
            "",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            summary,
            "",
        ]

        if kpis:
            parts.extend(["## Key Performance Indicators", "", "| Metric | Value | Average | Trend |", "|--------|-------|---------|-------|"])
            for kpi in kpis:
                trend_icon = "↑" if kpi.get("trend") == "up" else "↓" if kpi.get("trend") == "down" else "→"
                parts.append(f"| {kpi.get('title', 'N/A')} | {kpi.get('value', 'N/A')} | {kpi.get('mean', 'N/A')} | {trend_icon} |")
            parts.append("")

        if insights:
            parts.extend(["## AI Insights", ""])
            for i, insight in enumerate(insights, 1):
                parts.append(f"{i}. {insight}")
            parts.append("")

        if recommendations:
            parts.extend(["## Recommendations", ""])
            for i, rec in enumerate(recommendations, 1):
                parts.append(f"{i}. {rec}")
            parts.append("")

        if etl_logs:
            parts.extend(["## ETL Pipeline Logs", "", "| Step | Status | Timestamp |", "|------|--------|-----------|"])
            for log in etl_logs:
                parts.append(f"| {log.get('step', 'N/A')} | {log.get('status', 'N/A')} | {log.get('timestamp', 'N/A')} |")
            parts.append("")

        if chart_html:
            parts.extend(["## Visualizations", ""])
            parts.extend(chart_html)

        parts.append("")
        parts.append("---")
        parts.append(f"*Report generated by AI Analytics & ETL Copilot*")
        return "\n".join(parts)

    @staticmethod
    def generate_html_report(
        title: str,
        summary: str,
        kpis: list[dict[str, Any]] | None = None,
        insights: list[str] | None = None,
        charts: list[str] | None = None,
        etl_logs: list[dict[str, Any]] | None = None,
        recommendations: list[str] | None = None,
    ) -> str:
        kpi_html = ""
        if kpis:
            cards = []
            for kpi in kpis:
                trend_color = "#4CAF50" if kpi.get("trend") == "up" else "#f44336" if kpi.get("trend") == "down" else "#FFC107"
                cards.append(f"""
                <div style="background:#1e1e1e;border-radius:10px;padding:20px;margin:10px;flex:1;min-width:200px;box-shadow:0 2px 8px rgba(0,0,0,0.3);">
                    <h3 style="color:#888;margin:0;font-size:14px;">{kpi.get('title', '')}</h3>
                    <p style="font-size:28px;font-weight:bold;margin:10px 0;color:#fff;">{kpi.get('value', '')}</p>
                    <p style="color:#666;margin:0;">Avg: {kpi.get('mean', '')} <span style="color:{trend_color};">{'↑' if kpi.get('trend') == 'up' else '↓' if kpi.get('trend') == 'down' else '→'}</span></p>
                </div>""")
            kpi_html = f'<div style="display:flex;flex-wrap:wrap;margin:20px 0;">{"".join(cards)}</div>'

        insights_html = ""
        if insights:
            items = "".join(f"<li style='margin:8px 0;color:#ccc;'>{insight}</li>" for insight in insights)
            insights_html = f"<h2 style='color:#fff;'>AI Insights</h2><ul>{items}</ul>"

        recs_html = ""
        if recommendations:
            items = "".join(f"<li style='margin:8px 0;color:#ccc;'>{rec}</li>" for rec in recommendations)
            recs_html = f"<h2 style='color:#fff;'>Recommendations</h2><ul>{items}</ul>"

        etl_html = ""
        if etl_logs:
            rows = "".join(
                f"<tr><td style='padding:8px;border:1px solid #333;'>{log.get('step', '')}</td>"
                f"<td style='padding:8px;border:1px solid #333;'>{log.get('status', '')}</td>"
                f"<td style='padding:8px;border:1px solid #333;'>{log.get('timestamp', '')}</td></tr>"
                for log in etl_logs
            )
            etl_html = f"<h2 style='color:#fff;'>ETL Pipeline</h2><table style='width:100%;border-collapse:collapse;color:#ccc;'><tr><th style='padding:8px;border:1px solid #333;text-align:left;'>Step</th><th style='padding:8px;border:1px solid #333;text-align:left;'>Status</th><th style='padding:8px;border:1px solid #333;text-align:left;'>Timestamp</th></tr>{rows}</table>"

        charts_html = ""
        if charts:
            charts_html = f"<h2 style='color:#fff;'>Visualizations</h2>{''.join(charts)}"

        return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>{title}</title>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; background:#121212; color:#e0e0e0; padding:40px; }}
h1 {{ color:#fff; font-size:32px; margin-bottom:10px; }}
h2 {{ color:#fff; font-size:22px; margin:30px 0 15px; }}
.summary {{ background:#1e1e1e; border-radius:10px; padding:25px; margin:20px 0; line-height:1.8; }}
.footer {{ text-align:center; margin-top:40px; padding:20px; color:#666; border-top:1px solid #333; }}
</style>
</head>
<body>
<h1>{title}</h1>
<p style="color:#888;">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
<hr style="border-color:#333;margin:20px 0;">
<h2>Executive Summary</h2>
<div class="summary">{summary}</div>
{kpi_html}
{insights_html}
{recs_html}
{etl_html}
{charts_html}
<div class="footer">Report generated by AI Analytics &amp; ETL Copilot</div>
</body>
</html>"""

    @staticmethod
    def generate_analytics_summary(profile: dict[str, Any], validation: dict[str, Any], insights: list[str]) -> str:
        parts = [
            "## Analytics Summary",
            "",
            f"- **Dataset:** {profile.get('overview', {}).get('rows', 0):,} rows × {profile.get('overview', {}).get('columns', 0)} columns",
            f"- **Duplicates:** {profile.get('overview', {}).get('duplicate_pct', 0):.1f}%",
            f"- **Missing Values:** {profile.get('missing_summary', {}).get('total_missing', 0):,}",
            f"- **Memory:** {profile.get('overview', {}).get('memory_mb', 0):.2f} MB",
            "",
        ]
        for insight in insights:
            parts.append(f"- {insight}")
        return "\n".join(parts)


report_generator = ReportGenerator()
